version: "3"
services:
  cryfs:
    image: corruptsector/cryfs-lsyncd:latest
    privileged: true
    volumes:
      - ./example/config:/cryfs/config
      - ./example/sync:/cryfs/sync:ro
      - ./example/wireguard:/etc/wireguard/wg0.conf:ro
    environment:
      - CRYFS_PWD=password
      - BASE_DIR=10.253.1.1:/mnt/user/corruptsector/frigate
