version: "3"
services:
  cryfs:
    image: corruptsector/cryfs-lsyncd
    privileged: true
    volumes:
      - /cryfs/base:/cryfs/base
      - /cryfs/config:/cryfs/config
      - /cryfs/sync:/cryfs/sync
    environment:
      - CRYFS_PWD=password