version: "3"
services:
  cryfs:
    image: corruptsector/cryfs-lsyncd:dev
    privileged: true
    volumes:
      - ./base:/cryfs/base
      - ./config:/cryfs/config
      - ./sync:/cryfs/sync
    environment:
      - CRYFS_PWD=password